### ISSUE TITLE
运行失败

### ISSUE THREAD

**Issue by mrbig52** [ZiYang-xie/Hello_Fudan#6]
Error: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_801dda65-baa3-4e05-9960-6a74fdd2a463/582f3c4c-ff6f-436b-a8b1-008f1aafd488.tar.gz. return code: 2.

**Comment by ZiYang-xie** [comment]
好像是github的问题，重新run一遍就好了

**Comment by Ilgharkus** [comment]
我也遇到了这个Error，手动再运行一次就成功了。
